name: diffdock
channels:
  - pyg
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9.18
  - pip
  - python-devtools
  # Need older setuptools for openfold
  - setuptools=69.5.1
  # ProDy needs to be installed with conda
  - prody==2.2.0
  - scipy==1.12.0
  # Need to install torch in order to build openfold, so install it first
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu121
    - torch==2.5.1+cu121
    - torchvision==0.20.1+cu121
    - torchaudio==2.5.1+cu121
    - torch-geometric==2.5.3
    - torch-scatter==2.1.2
    - torch-sparse==0.6.18
    - torch-cluster==1.6.3
    - torch-spline-conv==1.2.2
    - torchmetrics==0.11.0
    - pytorch-lightning==1.9.5
    - dllogger @ git+https://github.com/NVIDIA/dllogger.git
    - e3nn==0.5.1
    - fair-esm[esmfold]==2.0.0
    - networkx==2.8.4
    - pandas==1.5.1
    - pybind11==2.11.1
    - rdkit==2022.03.3
    - scikit-learn==1.1.0
    - gradio==3.50.*
    - requests